### ISSUE TITLE
Deploying site

### ISSUE THREAD

**Issue by walter-grace** [joeboylson/react-portfolio-template#3]
I was curious what the best way to deploy this code would be. I tried using netlify but it seems with typescript it is tricky. Did you use gitpages? This repo is wonderful

**Comment by joeboylson** [comment]
@walter-grace 

Thanks so much! Appreciate the feedback.

I personally use Heroku for some other projects; it has a nice integration with Github and will rebuild every time you make a push to master (or you can specify a different branch if you want).

For Heroku, you just need to have a `"start"` script in your `package.json` that will run the production environment. For the Create-React App, they use [serve](https://www.npmjs.com/package/serve), which seems to be a pretty nice way to serve the files. I also really like Express, but that's more coding.

You also need to have a `"build"` command in your package.json - this command should be the react build process. (you shouldn't have to change it for this project)

So the whole process looks like:
1. you make a change and push it to master
2. Heroku sees that there's a change, and runs the deploy process
     a. install all node packages (so make sure you have `serve` in the dependency list)
     b. run the "build" command specified in your package.json
     c. run the "start" command specified in your package.json (just `serve -s build` for serve)
3. Takes a second to restart everything and BOOM, its live.

Hope this helps. Let me know if you got more questions. 👍

**Comment by joeboylson** [comment]
@walter-grace 

. . .  now that I look at this repo again (haven't for a long time), it looks like it does use github pages.

I think all you need to do is make sure you have a `gh-pages` branch in your project. And when you are ready to deploy, run `npm run deploy` (or `yarn deploy`) in your terminal. In the settings of your repo (Settings -> Options -> Github Pages), make sure you have the "source" pointing at your "gh-pages" branch.

And I think that's pretty much it.

Again, let me know if you got more questions.

**Comment by walter-grace** [comment]
@joeboylson thank you! i got it working with this last comment
